services:
- name: url-uploader-bot
  type: web
  env: python
  buildCommand: |
    apt-get update && apt-get install -y aria2
    pip install -r requirements.txt
  startCommand: python bot.py
  plan: free
  healthCheckPath: /health
  autoDeploy: true
  
  envVars:
  - key: API_ID
    value: "2819362"
  - key: API_HASH
    value: "578ce3d09fadd539544a327c45b55ee4"
  - key: BOT_TOKEN
    value: "8390475015:AAF8dauJYTWFwktTQABzG17_-JTN4r71R3M"
  
  disk:
    name: bot-data
    mountPath: /app/data
    sizeGB: 1
  
  region: frankfurt
  branch: main
